### ISSUE TITLE
Support default mapping for splitjoin

### ISSUE THREAD

**Issue by fagci** [kuntau/dotfiles#24]
https://github.com/kuntau/dotfiles/blob/b1af4bc689fc2de85c0b2b154f0d6ccc9f11cca4/config/nvim/lua/plugins.lua#L81

I think that `keys = { 'gS', 'gJ' }` need to be added to deal with default plugin mappings.

**Comment by kuntau** [comment]
Yup, we have that in `mappings.lua` https://github.com/kuntau/dotfiles/blob/b1af4bc689fc2de85c0b2b154f0d6ccc9f11cca4/config/nvim/lua/mappings.lua#L79-L81
